/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppPrayerRouteImport } from './routes/app.prayer'
import { Route as AppMilestonesRouteImport } from './routes/app.milestones'
import { Route as AppMeetingsRouteImport } from './routes/app.meetings'
import { Route as AppHabitsRouteImport } from './routes/app.habits'
import { Route as AppGroupsRouteImport } from './routes/app.groups'
import { Route as AppFollowUpsRouteImport } from './routes/app.follow-ups'
import { Route as AppDisciplesRouteImport } from './routes/app.disciples'
import { Route as AppDisciplesIdRouteImport } from './routes/app.disciples.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppPrayerRoute = AppPrayerRouteImport.update({
  id: '/prayer',
  path: '/prayer',
  getParentRoute: () => AppRoute,
} as any)
const AppMilestonesRoute = AppMilestonesRouteImport.update({
  id: '/milestones',
  path: '/milestones',
  getParentRoute: () => AppRoute,
} as any)
const AppMeetingsRoute = AppMeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => AppRoute,
} as any)
const AppHabitsRoute = AppHabitsRouteImport.update({
  id: '/habits',
  path: '/habits',
  getParentRoute: () => AppRoute,
} as any)
const AppGroupsRoute = AppGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AppRoute,
} as any)
const AppFollowUpsRoute = AppFollowUpsRouteImport.update({
  id: '/follow-ups',
  path: '/follow-ups',
  getParentRoute: () => AppRoute,
} as any)
const AppDisciplesRoute = AppDisciplesRouteImport.update({
  id: '/disciples',
  path: '/disciples',
  getParentRoute: () => AppRoute,
} as any)
const AppDisciplesIdRoute = AppDisciplesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppDisciplesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/disciples': typeof AppDisciplesRouteWithChildren
  '/app/follow-ups': typeof AppFollowUpsRoute
  '/app/groups': typeof AppGroupsRoute
  '/app/habits': typeof AppHabitsRoute
  '/app/meetings': typeof AppMeetingsRoute
  '/app/milestones': typeof AppMilestonesRoute
  '/app/prayer': typeof AppPrayerRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/app/disciples/$id': typeof AppDisciplesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/auth': typeof AuthRoute
  '/app/disciples': typeof AppDisciplesRouteWithChildren
  '/app/follow-ups': typeof AppFollowUpsRoute
  '/app/groups': typeof AppGroupsRoute
  '/app/habits': typeof AppHabitsRoute
  '/app/meetings': typeof AppMeetingsRoute
  '/app/milestones': typeof AppMilestonesRoute
  '/app/prayer': typeof AppPrayerRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app': typeof AppIndexRoute
  '/app/disciples/$id': typeof AppDisciplesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/disciples': typeof AppDisciplesRouteWithChildren
  '/app/follow-ups': typeof AppFollowUpsRoute
  '/app/groups': typeof AppGroupsRoute
  '/app/habits': typeof AppHabitsRoute
  '/app/meetings': typeof AppMeetingsRoute
  '/app/milestones': typeof AppMilestonesRoute
  '/app/prayer': typeof AppPrayerRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/app/disciples/$id': typeof AppDisciplesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/app'
    | '/auth'
    | '/app/disciples'
    | '/app/follow-ups'
    | '/app/groups'
    | '/app/habits'
    | '/app/meetings'
    | '/app/milestones'
    | '/app/prayer'
    | '/app/reports'
    | '/app/settings'
    | '/app/'
    | '/app/disciples/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/auth'
    | '/app/disciples'
    | '/app/follow-ups'
    | '/app/groups'
    | '/app/habits'
    | '/app/meetings'
    | '/app/milestones'
    | '/app/prayer'
    | '/app/reports'
    | '/app/settings'
    | '/app'
    | '/app/disciples/$id'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/app'
    | '/auth'
    | '/app/disciples'
    | '/app/follow-ups'
    | '/app/groups'
    | '/app/habits'
    | '/app/meetings'
    | '/app/milestones'
    | '/app/prayer'
    | '/app/reports'
    | '/app/settings'
    | '/app/'
    | '/app/disciples/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/prayer': {
      id: '/app/prayer'
      path: '/prayer'
      fullPath: '/app/prayer'
      preLoaderRoute: typeof AppPrayerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/milestones': {
      id: '/app/milestones'
      path: '/milestones'
      fullPath: '/app/milestones'
      preLoaderRoute: typeof AppMilestonesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/meetings': {
      id: '/app/meetings'
      path: '/meetings'
      fullPath: '/app/meetings'
      preLoaderRoute: typeof AppMeetingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/habits': {
      id: '/app/habits'
      path: '/habits'
      fullPath: '/app/habits'
      preLoaderRoute: typeof AppHabitsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/groups': {
      id: '/app/groups'
      path: '/groups'
      fullPath: '/app/groups'
      preLoaderRoute: typeof AppGroupsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/follow-ups': {
      id: '/app/follow-ups'
      path: '/follow-ups'
      fullPath: '/app/follow-ups'
      preLoaderRoute: typeof AppFollowUpsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/disciples': {
      id: '/app/disciples'
      path: '/disciples'
      fullPath: '/app/disciples'
      preLoaderRoute: typeof AppDisciplesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/disciples/$id': {
      id: '/app/disciples/$id'
      path: '/$id'
      fullPath: '/app/disciples/$id'
      preLoaderRoute: typeof AppDisciplesIdRouteImport
      parentRoute: typeof AppDisciplesRoute
    }
  }
}

interface AppDisciplesRouteChildren {
  AppDisciplesIdRoute: typeof AppDisciplesIdRoute
}

const AppDisciplesRouteChildren: AppDisciplesRouteChildren = {
  AppDisciplesIdRoute: AppDisciplesIdRoute,
}

const AppDisciplesRouteWithChildren = AppDisciplesRoute._addFileChildren(
  AppDisciplesRouteChildren,
)

interface AppRouteChildren {
  AppDisciplesRoute: typeof AppDisciplesRouteWithChildren
  AppFollowUpsRoute: typeof AppFollowUpsRoute
  AppGroupsRoute: typeof AppGroupsRoute
  AppHabitsRoute: typeof AppHabitsRoute
  AppMeetingsRoute: typeof AppMeetingsRoute
  AppMilestonesRoute: typeof AppMilestonesRoute
  AppPrayerRoute: typeof AppPrayerRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDisciplesRoute: AppDisciplesRouteWithChildren,
  AppFollowUpsRoute: AppFollowUpsRoute,
  AppGroupsRoute: AppGroupsRoute,
  AppHabitsRoute: AppHabitsRoute,
  AppMeetingsRoute: AppMeetingsRoute,
  AppMilestonesRoute: AppMilestonesRoute,
  AppPrayerRoute: AppPrayerRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
